### ISSUE TITLE
Receiving errors while applying Simple Website CMS Community template via directus-template-cli

### ISSUE THREAD

**Issue by Bossieh** [directus-labs/directus-templates#11]
I am receiving errors while applying the Simple Website CMS Community template via the directus-template-cli

Version info:
Directus: 11.4.0
Database: MySQL 9.1.0

Errors:

```
Loading data for 22 collections... done
-- Request failed. Retrying after 1000ms
-- Retrying job (attempt 1)
-- Request failed. Retrying after 2000ms
-- Retrying job (attempt 2)
-- Request failed. Retrying after 4000ms
-- Retrying job (attempt 3)
-- Max retries reached, not retrying further
 ›   Warning: Directus Error: alter table `block_button` add primary key `block_button_pkey`(`id`) - Multiple primary key defined (Status: 500) {"code":"INTERNAL_SERVER_ERROR"}
-- Request failed. Retrying after 1000ms
-- Retrying job (attempt 1)
-- Request failed. Retrying after 2000ms
-- Retrying job (attempt 2)
-- Request failed. Retrying after 4000ms
-- Retrying job (attempt 3)
-- Max retries reached, not retrying further
 ›   Warning: Directus Error: alter table `block_button_group` add primary key `block_button_group_pkey`(`id`) - Multiple primary key defined (Status: 500) {"code":"INTERNAL_SERVER_ERROR"}
-- Request failed. Retrying after 1000ms
-- Retrying job (attempt 1)
-- Request failed. Retrying after 2000ms
-- Retrying job (attempt 2)
-- Request failed. Retrying after 4000ms
-- Retrying job (attempt 3)
-- Max retries reached, not retrying further
 ›   Warning: Directus Error: alter table `block_form` add primary key `block_form_pkey`(`id`) - Multiple primary key defined (Status: 500) {"code":"INTERNAL_SERVER_ERROR"}
-- Request failed. Retrying after 1000ms
-- Retrying job (attempt 1)
-- Request failed. Retrying after 2000ms
-- Retrying job (attempt 2)
-- Request failed. Retrying after 4000ms
-- Retrying job (attempt 3)
-- Max retries reached, not retrying further
 ›   Warning: Directus Error: alter table `block_gallery` add primary key `block_gallery_pkey`(`id`) - Multiple primary key defined (Status: 500) {"code":"INTERNAL_SERVER_ERROR"}
-- Request failed. Retrying after 1000ms
-- Retrying job (attempt 1)
-- Request failed. Retrying after 2000ms
-- Retrying job (attempt 2)

**Comment by philipp-winterle** [comment]
### Current Behaviour

The usage of `npx directus-template-cli@latest apply` results in errors but partially installed collections without finished relations and missing content. 

### Expected Behaviour

The template is installed and no errors happen during installation

### Specifications

- Directus 11.4
- MySQL 8.4.4
- Template: agencyos / simplecms
- Collation of all tables (also newly added): utf8mb4_0900_ai_ci
- Connection with admin api key and email/pass

### Speculation

Maybe this is related to how the how directus gets the data by api request. 

### Error Log

```
[14:39:14] POST /collections 200 47ms
[14:39:14.709] ERROR: Unexpected token '_', "_utf8mb4\'[]\'" is not valid JSON
    err: {
      "type": "SyntaxError",
      "message": "Unexpected token '_', \"_utf8mb4\\'[]\\'\" is not valid JSON",
      "stack":
tcms_nginx         | 192.168.155.1 - - [24/Jan/2025:14:39:14 +0000] "POST /collections HTTP/1.1" 200 554 "-" "node" "-"
          SyntaxError: Unexpected token '_', "_utf8mb4\'[]\'" is not valid JSON
              at JSON.parse (<anonymous>)
              at parseJSON (file:///directus/node_modules/.pnpm/@directus+utils@file+packages+utils_vue@3.5.13_typescript@5.7.3_/node_modules/@directus/utils/dist/shared/index.js:131:15)
              at castToObject (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.10.5_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3____rwsrw2ii2kgfeysgzcibtnsnku/node_modules/@directus/api/dist/utils/get-default-value.js:47:20)
              at getDefaultValue (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.10.5_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3____rwsrw2ii2kgfeysgzcibtnsnku/node_modules/@directus/api/dist/utils/get-default-value.js:21:20)
              at file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.10.5_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3____rwsrw2ii2kgfeysgzcibtnsnku/node_modules/@directus/api/dist/utils/get-schema.js:111:35
              at file:///directus/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/mapValues.js:38:34
              at file:///directus/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_createBaseFor.js:17:11
              at baseForOwn (file:///directus/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/_baseForOwn.js:13:20)
              at mapValues (file:///directus/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/mapValues.js:37:3)
              at getDatabaseSchema (file:///directus/node_modules/.pnpm/@directus+api@file+api_@types+node@22.10.5_@unhead+vue@1.11.15_vue@3.5.13_typescript@5.7.3____rwsrw2ii2kgfeysgzcibtnsnku/node_modules/@directus/api/dist/utils/get-schema.js:108:21)
    }
```

```
[15:02:46.293] ERROR: alter table `block_gallery` add primary key `block_gallery_pkey`(`id`) - Multiple primary key defined
    err: {
      "type": "Error",
      "message": "alter table `block_gallery` add primary key `block_gallery_pkey`(`id`) - Multiple primary key defined",
      "stack":
          Error: alter table `block_gallery` add primary key `block_gallery_pkey`(`id`) - Multiple primary key defined
              at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/packets/packet.js:740:17)
              at Query.execute (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/commands/command.js:29:26)
              at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:475:34)
              at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:93:12)
              at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/packet_parser.js:75:16)
              at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:100:25)
              at Socket.emit (node:events:524:28)
              at addChunk (node:internal/streams/readable:561:12)
              at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
              at Readable.push (node:internal/streams/readable:392:5)
      "code": "ER_MULTIPLE_PRI_KEY",
      "errno": 1068,
      "sqlState": "42000",
      "sqlMessage": "Multiple primary key defined",
      "sql": "alter table `block_gallery` add primary key `block_gallery_pkey`(`id`)",
      "extensions": {
        "stack":
            Error: alter table `block_gallery` add primary key `block_gallery_pkey`(`id`) - Multiple primary key defined
                at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/packets/packet.js:740:17)
                at Query.execute (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/commands/command.js:29:26)
                at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:475:34)
                at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:93:12)
                at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/packet_parser.js:75:16)
                at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.12.0/node_modules/mysql2/lib/base/connection.js:100:25)
                at Socket.emit (node:events:524:28)
                at addChunk (node:internal/streams/readable:561:12)
                at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
                at Readable.push (node:internal/streams/readable:392:5)
      }
    }

```

**Comment by QuentinScDS** [comment]
Hello,
Same problem, nobody cares ?

**Comment by skf-funzt** [comment]
I had a similar issue with `EACCES` issue on applying the CMS template right after creating a fresh project.

With a permission fix service on the volumes of the default `docker-compose.yaml` the template can be applied without any issues.

The changes to add are:

```yaml
name: directus-cms-template
services:
  ...

  fix-volumes-permissions:
    image: alpine:latest
    container_name: fix-directus-permissions
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    command: >
      sh -c "chown -R 1000:1000 /directus/uploads /directus/extensions"
    restart: "no"

  directus:
    ...
    depends_on:
      fix-volumes-permissions:
        condition: service_completed_successfully
        ...
    ...

```

<details>

<summary>The complete `docker-compose.yaml` for reference</summary>

```yaml
name: directus-cms-template
services:
  database:
    image: postgis/postgis:16-master
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}', '-d', '${DB_DATABASE}', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  cache:
    image: redis:6
    healthcheck:
      test: ['CMD-SHELL', "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  fix-volumes-permissions:
    image: alpine:latest
    container_name: fix-directus-permissions
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    command: >
      sh -c "chown -R 1000:1000 /directus/uploads /directus/extensions"
    restart: "no"

  directus:
    image: directus/directus:11.12.0
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    depends_on:
      fix-volumes-permissions:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: ${CACHE_ENABLED}
      CACHE_AUTO_PURGE: ${CACHE_AUTO_PURGE}
      CACHE_STORE: 'redis'
      REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}

      PUBLIC_URL: ${PUBLIC_URL}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}

      REFRESH_TOKEN_COOKIE_SECURE: ${REFRESH_TOKEN_COOKIE_SECURE}
      REFRESH_TOKEN_COOKIE_SAME_SITE: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
      REFRESH_TOKEN_DOMAIN: ${REFRESH_TOKEN_COOKIE_DOMAIN}

      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_SAME_SITE: ${SESSION_COOKIE_SAME_SITE}
      SESSION_COOKIE_DOMAIN: ${SESSION_COOKIE_DOMAIN}

      EXTENSIONS_PATH: ${EXTENSIONS_PATH}
      EXTENSIONS_AUTO_RELOAD: ${EXTENSIONS_AUTO_RELOAD}
      EXTENSIONS_ROLLDOWN: ${EXTENSIONS_ROLLDOWN}

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: ${CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC}

      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

```

</details>
